version: '3'
services:
  django-polls:
    build: .
    image: yumemo/django-polls
    container_name: django-polls
    hostname: django-polls
    tty: true
    volumes:
      - .:/opt/app
    ports:
      - "8000:8000"