version: '3'
services:
  django-polls:
    build: .
    container_name: django-polls-container
    hostname: django-polls-container
    tty: true
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"